In [4]:
# Import Dependencies
import pandas as pd
from sqlalchemy import create_engine

In [5]:
# Read in CSVs
df1 = pd.read_csv("OSMI 2019 Mental Health in Tech Survey Results.csv")
df2 = pd.read_csv("OSMI 2020 Mental Health in Tech Survey Results cleaned.csv")
df3 = pd.read_csv("OSMI Mental Health in Tech Survey 2018.csv")
df4 = pd.read_csv("OSMI Mental Health in Tech Survey 2017.csv")
df5 = pd.read_csv("OSMI Mental Health in Tech 2016 Survey Results.csv")

In [6]:
# Merge CSVs
final_df = pd.concat([df1,df2,df3,df4,df5]).reset_index(drop=True)
final_df.to_csv("mergedmentalhealth.csv",index=False)
final_df

,year,tech_company,employer_benefits,know_options,employer_discussed_benefits,employer_resources,anonymity,difficulty_leave,comfortable_discussing,employer_discussed_issues,physical_importance,mental_importance,industry_support,age,gender,country
0,2019,True,I don't know,No,Yes,Yes,I don't know,Very easy,Yes,False,5.0,5.0,4.0,25,M,United States of America
1,2019,True,Yes,No,No,Yes,Yes,I don't know,Maybe,False,5.0,7.0,1.0,51,M,United States of America
2,2019,True,I don't know,No,No,I don't know,I don't know,Somewhat difficult,No,False,5.0,4.0,2.0,27,M,United States of America
3,2019,True,I don't know,No,Yes,Yes,Yes,Very easy,Yes,False,1.0,3.0,3.0,37,M,United States of America
4,2019,True,I don't know,No,I don't know,I don't know,I don't know,I don't know,No,False,4.0,4.0,3.0,46,M,United States of America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2604,2016,True,I don't know,I am not sure,No,I don't know,I don't know,Somewhat easy,Maybe,NaN,NaN,NaN,NaN,26,F,Canada
2605,2016,True,Yes,No,No,No,Yes,Somewhat easy,Yes,NaN,NaN,NaN,NaN,38,F,United States of America
2606,2016,True,Yes,Yes,Yes,Yes,I don't know,Somewhat difficult,Yes,NaN,NaN,NaN,NaN,52,M,United States of America
2607,2016,False,I don't know,I am not sure,No,Yes,I don't know,Somewhat difficult,Yes,NaN,NaN,NaN,NaN,30,F,United States of America
2608,2016,True,Yes,No,No,No,I don't know,Very difficult,Maybe,NaN,NaN,NaN,NaN,25,NB,Canada

In [7]:
# Create database connection
# change the owner name, password and port number based on your local situation
# engine = create_engine(f'postgresql://{*database_owner}:{*password}@localhost:{*port}/housing_db')
rds_connection_string = "postgres:postgres@localhost:5433/mentalhealth_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [8]:
# Confirm tables
engine.table_names()

['mental_health']

In [9]:
# Load dataframes into databases
final_df.to_sql(name = 'mental_health', con = engine, if_exists = 'append', index = False)

In [10]:
# Confirm data has been added by querying the income_tax table
pd.read_sql_query('select * from mental_health', con=engine).head()

,year,tech_company,employer_benefits,know_options,employer_discussed_benefits,employer_resources,anonymity,difficulty_leave,comfortable_discussing,employer_discussed_issues,physical_importance,mental_importance,industry_support,age,gender,country
0,2019,True,I don't know,No,Yes,Yes,I don't know,Very easy,Yes,False,5.0,5.0,4.0,25,M,United States of America
1,2019,True,Yes,No,No,Yes,Yes,I don't know,Maybe,False,5.0,7.0,1.0,51,M,United States of America
2,2019,True,I don't know,No,No,I don't know,I don't know,Somewhat difficult,No,False,5.0,4.0,2.0,27,M,United States of America
3,2019,True,I don't know,No,Yes,Yes,Yes,Very easy,Yes,False,1.0,3.0,3.0,37,M,United States of America
4,2019,True,I don't know,No,I don't know,I don't know,I don't know,I don't know,No,False,4.0,4.0,3.0,46,M,United States of America