In [8]:
# Import Dependencies
import pandas as pd
from sqlalchemy import create_engine

In [9]:
# Read in CSVs
df1 = pd.read_csv("Resources/OSMI 2019 Mental Health in Tech Survey Results.csv")
df2 = pd.read_csv("Resources/OSMI 2020 Mental Health in Tech Survey Results cleaned.csv")
df3 = pd.read_csv("Resources/OSMI Mental Health in Tech Survey 2018.csv")
df4 = pd.read_csv("Resources/OSMI Mental Health in Tech Survey 2017.csv")
df5 = pd.read_csv("Resources/OSMI Mental Health in Tech 2016 Survey Results.csv")

In [17]:
# Merge CSVs
final_df = pd.concat([df1,df2,df3,df4,df5]).reset_index(drop=True)
final_df = final_df.dropna()
final_df.to_csv("mergedmentalhealth.csv",index=False)
final_df

,year,tech_company,employer_benefits,know_options,employer_discussed_benefits,employer_resources,anonymity,difficulty_leave,comfortable_discussing,employer_discussed_issues,physical_importance,mental_importance,industry_support,age,gender,country
0,2019,True,I don't know,No,Yes,Yes,I don't know,Very easy,Yes,False,5.0,5.0,4.0,25,M,United States of America
1,2019,True,Yes,No,No,Yes,Yes,I don't know,Maybe,False,5.0,7.0,1.0,51,M,United States of America
2,2019,True,I don't know,No,No,I don't know,I don't know,Somewhat difficult,No,False,5.0,4.0,2.0,27,M,United States of America
3,2019,True,I don't know,No,Yes,Yes,Yes,Very easy,Yes,False,1.0,3.0,3.0,37,M,United States of America
4,2019,True,I don't know,No,I don't know,I don't know,I don't know,I don't know,No,False,4.0,4.0,3.0,46,M,United States of America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,2017,True,Yes,Yes,No,No,Yes,Somewhat easy,Yes,True,4.0,5.0,4.0,29,M,United States of America
1459,2017,False,I don't know,No,No,No,I don't know,Difficult,No,False,7.0,0.0,1.0,38,M,United States of America
1460,2017,True,I don't know,No,No,I don't know,Yes,Very easy,Yes,False,6.0,6.0,3.0,41,M,United Kingdom
1461,2017,True,Yes,No,I don't know,No,Yes,Very easy,Yes,True,8.0,4.0,3.0,40,M,United States of America
1462,2017,True,Yes,Yes,No,No,No,Very easy,Yes,True,6.0,4.0,2.0,30,M,United States of America

In [18]:
# Create database connection
# change the owner name, password and port number based on your local situation
# engine = create_engine(f'postgresql://{*database_owner}:{*password}@localhost:{*port}/housing_db')
rds_connection_string = "postgres:delilahjones@localhost:5432/mentalhealth_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [19]:
# Confirm tables
engine.table_names()

<ipython-input-19-2d97e9123e98>:2: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['mental_health']

In [20]:
# Load dataframes into databases
final_df.to_sql(name = 'mental_health', con = engine, if_exists = 'append', index = False)

In [21]:
# Confirm data has been added by querying the income_tax table
pd.read_sql_query('select * from mental_health', con=engine).head()

,year,tech_company,employer_benefits,know_options,employer_discussed_benefits,employer_resources,anonymity,difficulty_leave,comfortable_discussing,employer_discussed_issues,physical_importance,mental_importance,industry_support,age,gender,country
0,2019,True,I don't know,No,Yes,Yes,I don't know,Very easy,Yes,False,5.0,5.0,4.0,25,M,United States of America
1,2019,True,Yes,No,No,Yes,Yes,I don't know,Maybe,False,5.0,7.0,1.0,51,M,United States of America
2,2019,True,I don't know,No,No,I don't know,I don't know,Somewhat difficult,No,False,5.0,4.0,2.0,27,M,United States of America
3,2019,True,I don't know,No,Yes,Yes,Yes,Very easy,Yes,False,1.0,3.0,3.0,37,M,United States of America
4,2019,True,I don't know,No,I don't know,I don't know,I don't know,I don't know,No,False,4.0,4.0,3.0,46,M,United States of America